# Autogenerated wrapper script for minimap2_jll for x86_64-apple-darwin
export minimap2

using Zlib_jll
JLLWrappers.@generate_wrapper_header("minimap2")
JLLWrappers.@declare_library_product(minimap2, "@rpath/libminimap2.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_library_product(
        minimap2,
        "lib/libminimap2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
