# Autogenerated wrapper script for minimap2_jll for x86_64-linux-musl
export libminimap2

using Zlib_jll
JLLWrappers.@generate_wrapper_header("minimap2")
JLLWrappers.@declare_library_product(libminimap2, "libminimap2.so")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_library_product(
        libminimap2,
        "lib/libminimap2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
